"""Add Grant and project working scope

Revision ID: 0c1f25ef8dc8
Revises: 20260622_0010
Create Date: 2026-06-23 10:34:42.351278
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '0c1f25ef8dc8'
down_revision: str | None = '20260622_0010'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grants',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('local_user_id', sa.String(length=36), nullable=False),
    sa.Column('approval_mode', sa.Enum('ask_for_approval', 'approve_on_my_behalf', 'full_access', 'custom', name='approvalmode', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('repository_id', sa.String(length=36), nullable=True),
    sa.Column('project_working_scope_json', sa.JSON(), nullable=True),
    sa.Column('risk_ceiling', sa.Enum('R0', 'R1', 'R2', 'R3', 'R4', name='risklevel', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('allow_scope_expansion', sa.Boolean(), nullable=False),
    sa.Column('allow_new_files', sa.Boolean(), nullable=False),
    sa.Column('allow_protected_paths', sa.Boolean(), nullable=False),
    sa.Column('allow_high_risk_changes', sa.Boolean(), nullable=False),
    sa.Column('allow_danger_flag', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['local_user_id'], ['local_users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['repository_id'], ['project_repositories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_grants_local_user_id', 'grants', ['local_user_id'], unique=False)
    op.add_column('projects', sa.Column('working_scope_json', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'working_scope_json')
    op.drop_index('ix_grants_local_user_id', table_name='grants')
    op.drop_table('grants')
    # ### end Alembic commands ###
