"""add worker_runs

Revision ID: 20260622_0007
Revises: 20260622_0006
Create Date: 2026-06-22 13:47:52.726149
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = "20260622_0007"
down_revision: str | None = "20260622_0006"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "worker_runs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("local_user_id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("repository_id", sa.String(length=36), nullable=True),
        sa.Column("task_id", sa.String(length=36), nullable=False),
        sa.Column("task_attempt_id", sa.String(length=36), nullable=False),
        sa.Column("worker_id", sa.String(length=36), nullable=False),
        sa.Column("adapter_kind", sa.String(length=100), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "created",
                "running",
                "succeeded",
                "failed",
                "cancelled",
                "skipped",
                name="recordstatus",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("failed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("error_code", sa.String(length=100), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["local_user_id"],
            ["local_users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.ForeignKeyConstraint(
            ["repository_id"],
            ["project_repositories.id"],
        ),
        sa.ForeignKeyConstraint(
            ["task_attempt_id"],
            ["task_attempts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["tasks.id"],
        ),
        sa.ForeignKeyConstraint(
            ["worker_id"],
            ["workers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_worker_runs_attempt_id", "worker_runs", ["task_attempt_id"], unique=False)
    op.create_index("ix_worker_runs_task_id", "worker_runs", ["task_id"], unique=False)
    op.create_index("ix_worker_runs_worker_id", "worker_runs", ["worker_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_worker_runs_worker_id", table_name="worker_runs")
    op.drop_index("ix_worker_runs_task_id", table_name="worker_runs")
    op.drop_index("ix_worker_runs_attempt_id", table_name="worker_runs")
    op.drop_table("worker_runs")
    # ### end Alembic commands ###
