"""add_approval_requests_and_policy_decisions

Revision ID: 9c00b80c18e3
Revises: 20260622_0007
Create Date: 2026-06-22 15:03:58.797923
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '9c00b80c18e3'
down_revision: str | None = '20260622_0007'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('approval_requests',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('local_user_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('repository_id', sa.String(length=36), nullable=True),
    sa.Column('conversation_id', sa.String(length=36), nullable=True),
    sa.Column('agent_run_id', sa.String(length=36), nullable=True),
    sa.Column('tool_call_id', sa.String(length=36), nullable=True),
    sa.Column('task_id', sa.String(length=36), nullable=True),
    sa.Column('task_attempt_id', sa.String(length=36), nullable=True),
    sa.Column('git_worktree_id', sa.String(length=36), nullable=True),
    sa.Column('merge_review_id', sa.String(length=36), nullable=True),
    sa.Column('action_type', sa.String(length=100), nullable=False),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', 'stale', 'cancelled', 'expired', name='approvalstatus', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('scope_json', sa.JSON(), nullable=True),
    sa.Column('arguments_json', sa.JSON(), nullable=True),
    sa.Column('approval_fingerprint', sa.String(length=255), nullable=False),
    sa.Column('requested_by_session_id', sa.String(length=36), nullable=True),
    sa.Column('decided_by_session_id', sa.String(length=36), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('stale_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agent_runs.id'], ),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['decided_by_session_id'], ['sessions.id'], ),
    sa.ForeignKeyConstraint(['git_worktree_id'], ['git_worktrees.id'], ),
    sa.ForeignKeyConstraint(['local_user_id'], ['local_users.id'], ),
    sa.ForeignKeyConstraint(['merge_review_id'], ['merge_reviews.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['repository_id'], ['project_repositories.id'], ),
    sa.ForeignKeyConstraint(['requested_by_session_id'], ['sessions.id'], ),
    sa.ForeignKeyConstraint(['task_attempt_id'], ['task_attempts.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.ForeignKeyConstraint(['tool_call_id'], ['tool_calls.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_approval_requests_fingerprint', 'approval_requests', ['approval_fingerprint'], unique=False)
    op.create_index('ix_approval_requests_local_user_id', 'approval_requests', ['local_user_id'], unique=False)
    op.create_index('ix_approval_requests_task_attempt_id', 'approval_requests', ['task_attempt_id'], unique=False)
    op.create_table('policy_decisions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('local_user_id', sa.String(length=36), nullable=True),
    sa.Column('session_id', sa.String(length=36), nullable=True),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('repository_id', sa.String(length=36), nullable=True),
    sa.Column('task_id', sa.String(length=36), nullable=True),
    sa.Column('task_attempt_id', sa.String(length=36), nullable=True),
    sa.Column('tool_call_id', sa.String(length=36), nullable=True),
    sa.Column('approval_request_id', sa.String(length=36), nullable=True),
    sa.Column('action_type', sa.String(length=100), nullable=False),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('decision', sa.Enum('allow', 'approval_required', 'deny', name='policydecisionresult', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('context_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['approval_request_id'], ['approval_requests.id'], ),
    sa.ForeignKeyConstraint(['local_user_id'], ['local_users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['repository_id'], ['project_repositories.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.ForeignKeyConstraint(['task_attempt_id'], ['task_attempts.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.ForeignKeyConstraint(['tool_call_id'], ['tool_calls.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_policy_decisions_local_user_id', 'policy_decisions', ['local_user_id'], unique=False)
    op.create_index('ix_policy_decisions_task_attempt_id', 'policy_decisions', ['task_attempt_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_policy_decisions_task_attempt_id', table_name='policy_decisions')
    op.drop_index('ix_policy_decisions_local_user_id', table_name='policy_decisions')
    op.drop_table('policy_decisions')
    op.drop_index('ix_approval_requests_task_attempt_id', table_name='approval_requests')
    op.drop_index('ix_approval_requests_local_user_id', table_name='approval_requests')
    op.drop_index('ix_approval_requests_fingerprint', table_name='approval_requests')
    op.drop_table('approval_requests')
    # ### end Alembic commands ###
