"""add_process_runs

Revision ID: 49a6fdce6fff
Revises: 9c00b80c18e3
Create Date: 2026-06-22 15:38:11.033337
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = "49a6fdce6fff"
down_revision: str | None = "9c00b80c18e3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "process_runs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("local_user_id", sa.String(length=36), nullable=True),
        sa.Column("project_id", sa.String(length=36), nullable=True),
        sa.Column("repository_id", sa.String(length=36), nullable=True),
        sa.Column("task_id", sa.String(length=36), nullable=True),
        sa.Column("task_attempt_id", sa.String(length=36), nullable=True),
        sa.Column("worker_id", sa.String(length=36), nullable=True),
        sa.Column("worker_run_id", sa.String(length=36), nullable=True),
        sa.Column("tool_call_id", sa.String(length=36), nullable=True),
        sa.Column("command_display", sa.Text(), nullable=False),
        sa.Column("executable", sa.Text(), nullable=False),
        sa.Column("arguments_json", sa.JSON(), nullable=False),
        sa.Column("working_directory", sa.Text(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "created",
                "running",
                "succeeded",
                "failed",
                "timed_out",
                "cancelled",
                "blocked",
                name="processrunstatus",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("exit_code", sa.Integer(), nullable=True),
        sa.Column("timeout_seconds", sa.Integer(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("timed_out_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("failed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("stdout_artifact_id", sa.String(length=36), nullable=True),
        sa.Column("stderr_artifact_id", sa.String(length=36), nullable=True),
        sa.Column("combined_log_artifact_id", sa.String(length=36), nullable=True),
        sa.Column("error_code", sa.String(length=100), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["combined_log_artifact_id"],
            ["artifact_refs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["local_user_id"],
            ["local_users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.ForeignKeyConstraint(
            ["repository_id"],
            ["project_repositories.id"],
        ),
        sa.ForeignKeyConstraint(
            ["stderr_artifact_id"],
            ["artifact_refs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["stdout_artifact_id"],
            ["artifact_refs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["task_attempt_id"],
            ["task_attempts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["tasks.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tool_call_id"],
            ["tool_calls.id"],
        ),
        sa.ForeignKeyConstraint(
            ["worker_id"],
            ["workers.id"],
        ),
        sa.ForeignKeyConstraint(
            ["worker_run_id"],
            ["worker_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_process_runs_local_user_id", "process_runs", ["local_user_id"], unique=False
    )
    op.create_index(
        "ix_process_runs_task_attempt_id", "process_runs", ["task_attempt_id"], unique=False
    )
    op.create_index(
        "ix_process_runs_worker_run_id", "process_runs", ["worker_run_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_process_runs_worker_run_id", table_name="process_runs")
    op.drop_index("ix_process_runs_task_attempt_id", table_name="process_runs")
    op.drop_index("ix_process_runs_local_user_id", table_name="process_runs")
    op.drop_table("process_runs")
    # ### end Alembic commands ###
